services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\AdminTools\CacheClear\Service\ServiceInterface:
    class: OxidEsales\AdminTools\CacheClear\Service\Service
    arguments:
      $graphqlCache: '@?oxidesales.graphqlbase.cache'
