services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\AdminTools\Shared\Service\NamespaceMapper:
    tags: [ 'graphql_namespace_mapper' ]

  OxidEsales\AdminTools\Shared\Service\PermissionProvider:
    tags: [ 'graphql_permission_provider' ]